nftables-rs/nftables-rs

README.md
I noticed that the instructions in the README file haven't been updated yet. This PR proposes a trivial fix :)
=> docs: adjust installation instructions in README

src/schema.rs, tests/helper_tests.rs, tests/json_tests.rs, tests/serialize.rs
Previously adding an insert Rule directly to  an NfCmd::Insert was leaving out the necessary `{"insert": ...}` json object from the output.  By changing NfCmd::Insert to take an NfListObject, it matches how the ::Add command works and fixes the output.
=> Fix insert

src/schema.rs
Noticed the element was marked as "TODO", so I switched it on.
manually tested on linux 5.15 ubuntu 22.04
=> add element serialization

src/stmt.rs, tests/json_tests.rs
Set the `Queue` flags to be optional because they may not always be provided. For example running the below commands would result in an output `JSON` that would cause the library to return an error when parsing.
```bash
sudo nft add table ip mytable
sudo nft add chain ip mytable out-chain "{ type filter hook output priority 0;}"
sudo nft add rule ip mytable out-chain udp dport 20000 queue num 0
```
This `PR` fixes this issue by setting the queue flags as optional. An associated unit test has been added to verify functionality.
=> Update queue flags to be optional

src/expr.rs, src/stmt.rs
This MR fixes the following problems:
* Set item only support single elements
* XT only be parsed as `bool`
* Counter values are only u32.
=> Fix anonymous sets and XT

src/expr.rs
According to https://manpages.debian.org/testing/libnftables1/libnftables-json.5.en.html the key should be `tcp option`, not `tcpoption`.
Tested with the following rule:
`nft 'add rule ip mangle FORWARD tcp flags syn / syn,rst counter tcp option maxseg size set rt mtu'`
and the following example code:
```rust
use nftables::helper::get_current_ruleset;
fn main() {
let _set = get_current_ruleset(None, None).unwrap();
println!("Rules were parsed successfully");
}
```
Before the fix:
```
thread 'main' panicked at examples/pr.rs:4:48:
called `Result::unwrap()` on an `Err` value: NftInvalidJson(Error("data did not match any variant of untagged enum NfObject", line: 1, column: 1296))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After the fix:
```
Rules were …
```
=> Fix TCP option key name

src/expr.rs, src/schema.rs, tests/helper_tests.rs
A Verdict enum was moved from a NamedExpression to an Expression, placing it in a NamedExpression was a bug. Accroding to libnftables-json(5) (section VERDICT) a Verdict does not have a "verdict" key, it is "anonymous". e.g.: { "jump": { "target": "my_target"}, and not: { "verdict": { "jump": { "target": "my_target"} } }
Additionally a `Verdict::Jump` and a `Verdict::Goto` data was changed to a `stmt::JumpTarget` struct from a `String`.
A `Map` and a `Set` use almost the same fields, a map additinally uses a map field of type `String`.
=> Implement map support

src/expr.rs, src/schema.rs, tests/helper_tests.rs
* add a missing ifname SetType
* add a missing dynamic SetFlag
* add Elemn counter field
* change Elem fields to be Option
=> Add missing things

.github/workflows/rust.yml, tests/run_nft_tests.sh
Tests that use nft command alter the system's nftables.
By creating a fresh net namespace for each run, tests will not break system networking.
=> Run nft tests in netns

src/expr.rs, src/schema.rs, src/stmt.rs, src/types.rs
This PR adds some common traits (`Hash` and `Copy`) from [Rust's API guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html) to the crate's basic enum types.
I recently needed to create a HashMap using `(String, NfFamily)` as keys and couldn't since `NfFamily` didn't implement `Hash`. I added `Copy` as well for good measure since these enums are all 1 byte large.
=> Add common traits to basic enums

resources/test/json/tproxy.json, resources/test/nft/tproxy.nft, src/stmt.rs
This add supports for [TPROXY](https://docs.kernel.org/networking/tproxy.html#redirecting-traffic) which is not documented in the [man page](https://manpages.debian.org/unstable/libnftables1/libnftables-json.5.en.html)
=> feat: add support for tproxy

resources/test/json/basic.json, resources/test/json/counter.json, resources/test/json/nat.json, resources/test/json/nftables-init.json, resources/test/json/space-keys.json, resources/test/json/workstation.json, resources/test/json/workstation_combined.json, resources/test/nft/counter.nft, src/stmt.rs, tests/json_tests.rs
Changed `Counter` enum variants for serde to properly match named counters.
Old usage:
```rust
Statement::Counter(None)
```
New usage:
```rust
Statement::Counter(Counter::Anonymous(stmt::AnonymousCounter {
bytes: None,
packets: None,
}))
Statement::Counter(Counter::Named("count_packets".to_string()))
```
Closes #45.
=> Fix named counter statements

resources/test/json/synproxy.json, resources/test/nft-to-json.sh, resources/test/nft/synproxy.nft, src/schema.rs, src/stmt.rs, src/types.rs
SynProxy was missing, as it is not mentioned in the libnftables-json man page.
A few other statements were found to be implement in libnftables-json while not being documented by libnftables. TODO marks have been added for these statements.
Fixes #15.
=> Implement SynProxy

src/stmt.rs
Introducing `non-exhaustive` mark to `Statement` enum avoids future breaking changes when statements are added by forcing users to add a wildcard arm to match on statement.
Proposed in #70.
=> Mark Statement as non-exhaustive enum

README.md
This adds @JKRhb to the list of maintainers.
As a fellow project member of the [NAMIB project](https://github.com/namib-project) (2020-2022), Jan witnessed the inception of *nftables-rs* (which was named *nft-rs* at that time). Jan has made [multiple contributions](https://github.com/namib-project/nftables-rs/commits?author=JKRhb) to this project and reviews pull requests.
He was added as a co-owner of the [nftables crate](https://crates.io/crates/nftables) about 6 months ago and has had push access to this repository ever since.
Currently @jwhb and @JKRhb have exclusive push permissions to the GitHub repository and exclusive ownership of the crate.
There have been no recent security changes; this documentation update is solely for transparency.
=> Add @JKRhb as maintainer in README

resources/test/json/setmap.json, resources/test/nft/setmap.nft, src/lib.rs, src/schema.rs, src/types.rs, src/visitor.rs, tests/helper_tests.rs
This PR improves documentation, usability and correctness starting from the entrypoint `crate::schema`:
* Add/update doc comments throughout `crate::schema`.
* Add lib doc comment to `lib.rs`.
* Qualify `per` attribute of `schema::Limit` struct as `NfTimeUnit` enum (was `String`). (**breaking**)
* Add a new test for map.
* Add implementation of `Default` trait for table, chain, rule, set, map, element, flowtable, counter, quota, cthelper, limit, ruleset, metainfoobject, cttimeout.
* Remove some useless `::new()` functions (as replaced by `Default`). (possibly **breaking**)
* Replace `family: String` by `family: NfFamily` in flowtable, counter, quota, cthelper, limit. (**breaking**)
=> Add Default impl, improve doc comments, add NfTimeUnit to Limit

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, tests/deserialize.rs, tests/json_tests.rs
This PR adds [datatest-stable](https://github.com/nextest-rs/datatest-stable/issues) as a custom test harness.
Datatest generates a test for each file matching a glob. We can use this to generate a deserialization test for each test (json) file instead of looping through all json files within one test.
=> Generate deserialize tests with harness

README.md, src/batch.rs, src/expr.rs, src/helper.rs, src/schema.rs, src/stmt.rs, src/visitor.rs, tests/helper_tests.rs, tests/json_tests.rs, tests/serialize.rs
See each commit message for details.
These are a lot of breaking changes, so please take your time to check if they are properly done :)
=> Various memory optimizations

README.md, src/helper.rs, tests/helper_tests.rs
This improves the versatility of the API.
With the new API there are more ideomatic options for the user like
&Path, PathBuf and also still &str and more.
This is an API incompatible change.
I think it's not really possible to make this API compatible,
because the None-values need explicit type annotations due to the trait based API.
The default None-based API has been replaced by functions without arguments
to make the common case easier to use.
The user code changes are probably minimal in most cases, because None arguments
can just be removed and string arguments keep working as-is due to the std
implementations of AsRef.
Convenience constants are provided to make use of the None-arguments
to the _with_args() functions more readable and easier to use.
As a side effect this change also …
=> helper: Change API to AsRef<OsStr> based API

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, src/helper.rs
Basically integrates functions from the nftables_async crate here, with both tokio and async-process support behind feature gates.
Also corrected some of the behaviour differences in nftables_async, e.g. get_current_ruleset_raw passes additional arguments (keeping "-j list ruleset" intact) in nftables_async, but replaces the default arguments (except -j) here.
=> feat(helper): add async helpers

resources/test/json/nat.json, resources/test/nft/nat.nft, src/stmt.rs
Fixes #111 by allowing `Expression` as NAT `port`.
=> Fix NAT port ranges

src/expr.rs, src/lib.rs
This is a major improvement to the `expr` module:
* Adds doc comments throughout the module
* Adds `Default` impls for all structs in `expr`
* (**breaking**) Adds SocketAttr enum type for Socket `key`.
=> Add documentation for Expressions

Cargo.lock, Cargo.toml, README.md, src/cli.rs, src/expr.rs, src/lib.rs, src/main.rs, src/schema.rs, src/stmt.rs, src/types.rs
Hi,
thank you for this useful project. In addition to generate JSON I'd like to export the nice and explicit Rust types to a JSON Schema to use it in other scenarios as well. This PR adds basic support for generating a schema and export it to file.
The PR introduces an additional dependency (schemars) which can generate a schema by deriving the JSONSchema macro.
=> Add support for exporting JSON schema to file

.github/workflows/rust.yml
The *Rust* Actions workflow recently failed to run the user-netns tests due to:
```
unshare: write failed /proc/self/uid_map: Operation not permitted
```
This is likely due to a recent change in the runner image.
A fix suggested [here](https://github.com/actions/runner-images/issues/10443#issuecomment-2616616457) was applied. The custom AppArmor profile is not needed anymore.
=> ci: fix user network ns on actions

src/expr.rs
Payload offset is in fact given in bits. NFT manual is not very clear in that regard:
>RAW PAYLOAD EXPRESSION
>    @base,offset,length
>The raw payload expression instructs to load length bits starting at offset bits. Bit 0 refers to the very first bit --- in the C programming language, this corresponds to the topmost bit, i.e. 0x80 in case of an octet. They are useful to match headers that do not have a human-readable template expression yet. Note that nft will not add dependencies for Raw payload expressions. If you e.g. want to match protocol fields of a transport header with protocol number 5, you need to manually exclude packets that have a different transport header, for instance by using meta l4proto 5 before the raw expression.
>
>Inner Header / Payload, i.e. after the L4 …
=> Fix Payload docs in expr.rs

resources/test/json/bitflags.json, resources/test/nft/bitflags.nft, src/expr.rs, tests/json_tests.rs
Fixes #165
- changed BinaryOperation::OR to accept Vec<Expression> instead of exactly two.
- added regression test (tests/test_bit_flags)
- note: The fix was tested with deserialization only. I did not test adding an nftables rule with bit flags
=> fix: bitwise flags or with more than two operands
